namespace SwizzBotDisco.Games.HorseRacing.Utils;

public static class HorseNameGenerator
{
    private static readonly Random _random = new();

    private static readonly List<string> _names = new()
    {
        "Your Mortgage Is On Me",
        "Emotional Support Horse",
        "Butterface Stallion",
        "Spanks McCanter",
        "Daddy’s Tax Write-Off",
        "My Therapist Said No",
        "I Only Got Three Legs",
        "Carl Neighson",
        "Edward Gallophands",
        "Can’t Read Signals",
        "Midlife Canter",
        "Trot or Not",
        "My Ex Is Watching",
        "Yee Neigh",
        "Probable Cause",
        "I’m Horse and I Know It",
        "Mr. Worldwide (Equine Edition)",
        "Girth Brooks",
        "Thicc Stallion",
        "Wrong Turn Clyde",
        "Elmer’s Revenge",
        "Fast? Depends",
        "Big Mac on Hooves",
        "I Will Poop Mid-Race",
        "Certified Hay Eater",
        "I Lick Electric Fences",
        "Fifty Shades of Neigh",
        "Stallionaire",
        "ClipClop, Esq.",
        "Not a Phase, Mom",
        "Jeff",
        "Duct Tape and Hope",
        "Gassy Lassie",
        "Unqualified Stallion",
        "Hoovey McDoobie",
        "Speed Isn’t Everything",
        "Mildred the Menace",
        "Therapy Isn’t Working",
        "I Brought Snacks",
        "Tummy Ache Express",
        "Pastor Gallop",
        "I Fart in Corners",
        "Just Here for the Oats",
        "Nightmair",
        "Why Am I Sticky",
        "Nope Dotavius",
        "Can’t Even Gallop",
        "Reverse Uno",
        "Runnin' on Vibes",
        "Mr. Edibles",
        "Sir Poops-a-Lot",
        "NasHaycar",
        "Aunt Peggy’s Debt",
        "Emergency Brakes Gone",
        "Herbie Fully Horse",
        "They Neigh Me",
        "Jumped the Gun Twice",
        "2 Neigh 2 Furious",
        "Suburban Hay Dealer",
        "Unlicensed Trotter",
        "Flatulent Fury",
        "Buns of Hay",
        "Mcriblet",
        "Illegal in 3 States",
        "Glue Me Once",
        "I Ate a Rock",
        "Hoofnado",
        "Dwayne \"The Hoof\" Johnson",
        "Currently Stalling",
        "Captain Midpack",
        "Whinny the Glue",
        "Can’t Legally Race",
        "Definitely Not a Dog",
        "Equestrian Disappointment",
        "DMV Dropout",
        "Hay-Zeus Christ",
        "404 Horse Not Found",
        "Probable Winner",
        "Neighoncé",
        "Canter McGregor",
        "Gallopy Balboa",
        "Too Much Mayonnaise",
        "Zesty Zamboni",
        "Didn't Stretch First",
        "BeyonStable",
        "Horse Divorce Attorney",
        "Off-Track Baddie",
        "Infinite Gallop Loop",
        "Cinnamon Toast Clomp",
        "Flat Tire Fred",
        "DNF the Destroyer",
        "Statistically Irrelevant",
        "Shameless Trotter",
        "Neighbraska",
        "Moist Nugget",
        "The Canterbury Fail",
        "OSHA Violation",
        "Slipped in Turn 2",
        "Raced Once, Cried Twice",
        "Little Spoon Stallion"
    };

    public static string GetRandomName()
    {
        return _names[_random.Next(_names.Count)];
    }
}
